version: "3.9"

services:
  secutils:
    image: michaelborck/secutils
    container_name: secutils
    ports:
      - "6080:80"
    environment:
      - USER=root
      - PASSWORD=rootpassword
      - SSL=false
    command: ["/bin/sh", "-c", "/start.sh && exec /usr/bin/supervisord"]

  webserver:
    image: michaelborck/webserver
    container_name: webserver
    ports:
      - "8080:80"
      - "8443:443"

  ldap:
    image: osixia/openldap
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"

  mail:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - "8025:8025"
      - "1025:1025"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "exampledb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "userpassword"
    ports:
      - "3306:3306"

  telnet:
    image: mikesplain/telnet
    container_name: telnet
    ports:
      - "23:23"

  workstation:
    image: alpine:latest
    container_name: workstation
    command: /bin/sh -c "while true; do sleep 3600; done"

networks:
  default:
    name: sec-training
    ipam:
      config:
        - subnet: 172.20.0.0/24

